import logging
from datetime import date, datetime
from decimal import Decimal
from pathlib import Path
from typing import Any

from ..utils.base import BaseExporter


class SQLExporter(BaseExporter):
    """
    Exporter for SQL format output.
    Generates SQL INSERT statements for database import.
    """

    def __init__(
        self,
        table_name: str,
        dialect: str = "postgresql",
        batch_size: int = 1000,
        include_schema: str | None = None,
        logger: logging.Logger | None = None,
    ):
        """
        Initialize SQL exporter with database-specific options.

        Args:
            table_name: Name of the table/dataset being exported
            dialect: SQL dialect (postgresql, mysql, sqlite, mssql)
            batch_size: Number of records per INSERT statement
            include_schema: Optional schema name to prefix table name
            logger: Optional logger instance
        """
        super().__init__(table_name, logger)
        self.dialect = dialect.lower()
        self.batch_size = max(1, batch_size)  # Ensure at least 1
        self.include_schema = include_schema

        # Validate dialect
        supported_dialects = ["postgresql", "mysql", "sqlite", "mssql"]
        if self.dialect not in supported_dialects:
            raise ValueError(
                f"Unsupported SQL dialect: {dialect}. Supported: {supported_dialects}"
            )

    def export(self, data: list[dict[str, Any]], output_path: str) -> None:
        """
        Export data to SQL file with INSERT statements.

        Args:
            data: Generated data to export
            output_path: Path where the SQL should be exported

        Raises:
            ValueError: If data validation fails
            IOError: If file cannot be written
        """
        if not self.validate_data(data):
            raise ValueError("Data validation failed for SQL export")

        if not data:
            self.logger.warning("Empty dataset, creating empty SQL file")
            Path(output_path).touch()
            return

        try:
            # Ensure output directory exists
            output_file = Path(output_path)
            output_file.parent.mkdir(parents=True, exist_ok=True)

            self.logger.info(
                f"Exporting {len(data)} records to SQL ({self.dialect}): {output_path}"
            )

            with open(output_file, "w", encoding="utf-8") as sqlfile:
                # Write file header
                self._write_header(sqlfile)

                # Write data in batches
                field_names = list(data[0].keys())
                total_batches = (len(data) + self.batch_size - 1) // self.batch_size

                for batch_idx in range(0, len(data), self.batch_size):
                    batch_data = data[batch_idx : batch_idx + self.batch_size]
                    batch_num = (batch_idx // self.batch_size) + 1

                    self._write_batch_insert(
                        sqlfile, field_names, batch_data, batch_num, total_batches
                    )

                # Write file footer
                self._write_footer(sqlfile)

            self.logger.info(
                f"Successfully exported {len(data)} records to {output_path}"
            )

        except Exception as e:
            self.logger.error(f"Failed to export SQL to {output_path}: {e}")
            raise OSError(f"SQL export failed: {e}") from e

    def _write_header(self, file_handle) -> None:
        """Write SQL file header with comments and setup."""
        file_handle.write(
            f"-- Generated SQL INSERT statements for table: {self._get_full_table_name()}\n"
        )
        file_handle.write(f"-- SQL Dialect: {self.dialect.upper()}\n")
        file_handle.write("-- Generated by schema-faker\n\n")

        # Dialect-specific setup
        if self.dialect == "mysql":
            file_handle.write("SET FOREIGN_KEY_CHECKS=0;\n")
            file_handle.write("SET AUTOCOMMIT=0;\n")
            file_handle.write("START TRANSACTION;\n\n")
        elif self.dialect == "postgresql":
            file_handle.write("BEGIN;\n\n")
        elif self.dialect == "mssql":
            file_handle.write(
                f"SET IDENTITY_INSERT {self._get_full_table_name()} ON;\n"
            )
            file_handle.write("BEGIN TRANSACTION;\n\n")

    def _write_footer(self, file_handle) -> None:
        """Write SQL file footer with commit statements."""
        file_handle.write("\n")

        # Dialect-specific cleanup
        if self.dialect == "mysql":
            file_handle.write("COMMIT;\n")
            file_handle.write("SET FOREIGN_KEY_CHECKS=1;\n")
        elif self.dialect == "postgresql":
            file_handle.write("COMMIT;\n")
        elif self.dialect == "mssql":
            file_handle.write("COMMIT TRANSACTION;\n")
            file_handle.write(
                f"SET IDENTITY_INSERT {self._get_full_table_name()} OFF;\n"
            )
        elif self.dialect == "sqlite":
            file_handle.write("-- SQLite auto-commits by default\n")

    def _write_batch_insert(
        self,
        file_handle,
        field_names: list[str],
        batch_data: list[dict[str, Any]],
        batch_num: int,
        total_batches: int,
    ) -> None:
        """Write a batch INSERT statement."""
        if not batch_data:
            return

        # Write batch comment
        file_handle.write(
            f"-- Batch {batch_num} of {total_batches} ({len(batch_data)} records)\n"
        )

        # Start INSERT statement
        table_name = self._get_full_table_name()
        quoted_fields = [self._quote_identifier(field) for field in field_names]

        file_handle.write(
            f"INSERT INTO {table_name} ({', '.join(quoted_fields)}) VALUES\n"
        )

        # Write value rows
        for i, record in enumerate(batch_data):
            values = [self._format_value(record.get(field)) for field in field_names]
            value_clause = f"({', '.join(values)})"

            # Add comma except for last row
            if i < len(batch_data) - 1:
                value_clause += ","
            else:
                value_clause += ";"

            file_handle.write(f"  {value_clause}\n")

        file_handle.write("\n")

    def _get_full_table_name(self) -> str:
        """Get fully qualified table name with optional schema."""
        if self.include_schema:
            schema_quoted = self._quote_identifier(self.include_schema)
            table_quoted = self._quote_identifier(self.table_name)
            return f"{schema_quoted}.{table_quoted}"
        else:
            return self._quote_identifier(self.table_name)

    def _quote_identifier(self, identifier: str) -> str:
        """Quote SQL identifier based on dialect."""
        quote_chars = {"postgresql": '"', "mysql": "`", "sqlite": '"', "mssql": "["}

        quote_char = quote_chars.get(self.dialect, '"')

        if self.dialect == "mssql":
            return f"[{identifier}]"
        else:
            return f"{quote_char}{identifier}{quote_char}"

    def _format_value(self, value: Any) -> str:
        """Format a value for SQL insertion."""
        if value is None:
            return "NULL"
        elif isinstance(value, bool):
            # Handle boolean values
            if self.dialect in ["postgresql", "sqlite"]:
                return "TRUE" if value else "FALSE"
            else:  # mysql, mssql
                return "1" if value else "0"
        elif isinstance(value, int | float):
            return str(value)
        elif isinstance(value, Decimal):
            return str(value)
        elif isinstance(value, str):
            # Escape single quotes and wrap in quotes
            escaped = value.replace("'", "''")
            return f"'{escaped}'"
        elif isinstance(value, datetime):
            if self.dialect == "mssql":
                return f"'{value.strftime('%Y-%m-%d %H:%M:%S.%f')[:-3]}'"
            else:
                return f"'{value.strftime('%Y-%m-%d %H:%M:%S')}'"
        elif isinstance(value, date):
            return f"'{value.strftime('%Y-%m-%d')}'"
        else:
            # Convert other types to string
            escaped = str(value).replace("'", "''")
            return f"'{escaped}'"

    def export_multiple_tables(
        self,
        datasets: dict[str, list[dict[str, Any]]],
        output_dir: str,
        single_file: bool = False,
    ) -> dict[str, str]:
        """
        Export multiple datasets to SQL files.

        Args:
            datasets: Dictionary mapping table names to data lists
            output_dir: Directory to write SQL files
            single_file: If True, export all datasets to single SQL file

        Returns:
            Dictionary mapping table names to output file paths
        """
        output_dir_path = Path(output_dir)
        output_dir_path.mkdir(parents=True, exist_ok=True)

        exported_files = {}

        if single_file:
            # Export all datasets to single file
            combined_output_path = output_dir_path / "datasets.sql"
            self._export_combined_datasets(datasets, str(combined_output_path))

            # Return the same path for all tables
            for table_name in datasets.keys():
                exported_files[table_name] = str(combined_output_path)
        else:
            # Export each dataset to separate files
            for table_name, data in datasets.items():
                sql_filename = f"{table_name}.sql"
                output_path = output_dir_path / sql_filename

                # Create a separate exporter for each table
                table_exporter = SQLExporter(
                    table_name=table_name,
                    dialect=self.dialect,
                    batch_size=self.batch_size,
                    include_schema=self.include_schema,
                    logger=self.logger,
                )

                table_exporter.export(data, str(output_path))
                exported_files[table_name] = str(output_path)

        self.logger.info(
            f"Exported {len(datasets)} datasets to SQL ({self.dialect}) in {output_dir}"
        )

        return exported_files

    def _export_combined_datasets(
        self, datasets: dict[str, list[dict[str, Any]]], output_path: str
    ) -> None:
        """
        Export multiple datasets to a single SQL file.

        Args:
            datasets: Dictionary mapping table names to data lists
            output_path: Path for combined SQL file
        """
        try:
            total_records = sum(len(data) for data in datasets.values())

            with open(output_path, "w", encoding="utf-8") as sqlfile:
                # Write combined header
                sqlfile.write("-- Combined SQL INSERT statements for multiple tables\n")
                sqlfile.write(f"-- SQL Dialect: {self.dialect.upper()}\n")
                sqlfile.write(f"-- Tables: {', '.join(datasets.keys())}\n")
                sqlfile.write("-- Generated by schema-faker\n\n")

                # Dialect-specific setup
                if self.dialect == "mysql":
                    sqlfile.write("SET FOREIGN_KEY_CHECKS=0;\n")
                    sqlfile.write("SET AUTOCOMMIT=0;\n")
                    sqlfile.write("START TRANSACTION;\n\n")
                elif self.dialect == "postgresql":
                    sqlfile.write("BEGIN;\n\n")

                # Export each dataset
                for table_name, data in datasets.items():
                    if data:
                        sqlfile.write(f"-- Data for table: {table_name}\n")

                        # Temporarily change table name for this export
                        original_table_name = self.table_name
                        self.table_name = table_name

                        # Write data in batches
                        field_names = list(data[0].keys())
                        for batch_idx in range(0, len(data), self.batch_size):
                            batch_data = data[batch_idx : batch_idx + self.batch_size]
                            batch_num = (batch_idx // self.batch_size) + 1
                            total_batches = (
                                len(data) + self.batch_size - 1
                            ) // self.batch_size

                            self._write_batch_insert(
                                sqlfile,
                                field_names,
                                batch_data,
                                batch_num,
                                total_batches,
                            )

                        # Restore original table name
                        self.table_name = original_table_name

                        sqlfile.write("\n")

                # Write combined footer
                if self.dialect == "mysql":
                    sqlfile.write("COMMIT;\n")
                    sqlfile.write("SET FOREIGN_KEY_CHECKS=1;\n")
                elif self.dialect == "postgresql":
                    sqlfile.write("COMMIT;\n")

            self.logger.info(
                f"Successfully exported {len(datasets)} datasets "
                f"({total_records} total records) to {output_path}"
            )

        except Exception as e:
            self.logger.error(f"Failed to export combined SQL to {output_path}: {e}")
            raise OSError(f"Combined SQL export failed: {e}") from e

    def get_export_format(self) -> str:
        """
        Get the export format identifier.

        Returns:
            Format identifier string
        """
        return "sql"

    def validate_data(self, data: list[dict[str, Any]]) -> bool:
        """
        Enhanced validation for SQL export compatibility.

        Args:
            data: Data to validate

        Returns:
            True if data is valid for SQL export
        """
        # Use base validation first
        if not super().validate_data(data):
            return False

        if not data:
            return True

        # Validate SQL identifier compatibility
        first_record_keys = set(data[0].keys())

        for field_name in first_record_keys:
            if not self._is_valid_sql_identifier(field_name):
                self.logger.error(
                    f"Field name '{field_name}' is not a valid SQL identifier"
                )
                return False

        self.logger.debug(f"SQL validation passed for {len(data)} records")
        return True

    def _is_valid_sql_identifier(self, identifier: str) -> bool:
        """
        Check if string is a valid SQL identifier.

        Args:
            identifier: String to validate

        Returns:
            True if valid SQL identifier
        """
        if not identifier:
            return False

        # Check for SQL reserved words (basic check)
        sql_reserved = {
            "select",
            "from",
            "where",
            "insert",
            "update",
            "delete",
            "create",
            "drop",
            "alter",
            "table",
            "index",
            "view",
            "and",
            "or",
            "not",
            "null",
            "true",
            "false",
        }

        if identifier.lower() in sql_reserved:
            return False

        # Must start with letter or underscore, contain only alphanumeric and underscore
        import re

        return bool(re.match(r"^[a-zA-Z_][a-zA-Z0-9_]*$", identifier))
